#!/bin/sh

# This file solely defines what happens when the system is
# initialized, rebooted or shutdown. Services management is
# not its job (though it can call a service manager here).

SERVICES="hwclock syslog-ng dbus acpid iptables cron tor"

source /etc/init.d/rc.conf

init() {
	echo "[RC] Mounting filesystems..."
	# /dev, /sys, /proc are already mounted by mkinitcpio and moved to new root by switch_root
	# it seems run is also transferred by switch_root...
	mountpoint -q /proc || mount -t proc proc /proc -o nosuid,noexec,nodev
	mountpoint -q /sys || mount -t sysfs sys /sys -o nosuid,noexec,nodev
	mountpoint -q /dev || mount -t devtmpfs dev /dev -o mode=0755,nosuid
	mountpoint -q /run || mount -t tmpfs run /run -o mode=0755,nosuid,nodev
	mkdir -p /dev/{pts,shm}
	mountpoint -q /dev/shm || mount -t tmpfs tmpfs /dev/shm -o mode=1777,nosuid,nodev
	mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec

	echo "[RC] Remounting root read-only..."
	mount -o remount,ro /

	echo "[RC] Starting udev..."
	/usr/lib/systemd/systemd-udevd --daemon
	udevadm trigger --action=add --type=subsystems
	udevadm trigger --action=add --type=devices

	echo "[RC] Checking filesystems..."
	if ! fsck -ATa; then
		echo "fsck failed..."
		sleep 5; /opt/sbase/halt -p
	fi

	echo "[RC] Remounting root read-write..."
	mount -o remount,rw /

	echo "[RC] Creating the encrypted swap partition..."
	cryptsetup --key-file=/dev/urandom --cipher=aes-cbc-essiv:sha256 --key-size=256 open --type plain /dev/sda4 swap
	mkswap /dev/mapper/swap

	echo "[RC] Mounting filesystems and swap in fstab..."
	mount -a
	swapon -a

	echo "[RC] Setting hostname..."
	cat /etc/hostname >| /proc/sys/kernel/hostname

	echo "[RC] Setting up the lo device..."
	ip link set up dev lo

	echo "[RC] Getting random MAC addresses..."
	macchanger -Ab $ETHERNET_INTERFACE
	macchanger -Ab $WIFI_INTERFACE

	echo "[RC] Setting up keymap..."
	loadkeys $KEYMAP

	echo "[RC] Setting random seed..."
	[ -e /etc/random-seed ] && cp /etc/random-seed /dev/urandom
	dd if=/dev/urandom of=/etc/random-seed count=1 bs=512 2> /dev/null

	echo "[RC] Starting services..."
	for service in $SERVICES; do
		servman start "$service"
	done

	echo "[RC] Starting ttys..."
	/opt/sbase/bin/respawn -d 1 agetty --noclear -8 -s 38400 tty1 linux &
	/opt/sbase/bin/respawn -d 1 agetty --noclear -8 -s 38400 tty2 linux &
	/opt/sbase/bin/respawn -d 1 agetty --noclear -8 -s 38400 tty3 linux &
	/opt/sbase/bin/respawn -d 1 agetty --noclear -8 -s 38400 tty4 linux &
}

shutdown() {
	echo "[RC] Shutting down..."

	echo "[RC] Stopping services..."
	servman stop all

	echo "[RC] Storing random seed..."
	dd if=/dev/urandom of=/etc/random-seed count=1 bs=512 2> /dev/null
	
	echo "[RC] Killing all processes..."
	kill -s TERM -1
	sleep 3
	kill -s KILL -1

	echo "[RC] Unmounting swap and filesystems..."
	swapoff -a
	umount -a -r

	echo "[RC] Remounting root as read-only..."
	mount -o remount,ro /

	echo "[RC] Final sync, wait..."
	sync;sync
	sleep 3
	wait
}

case "$1" in
init)
	init;;
reboot)
	shutdown
	/opt/sbase/bin/halt -r;;
shutdown)
	shutdown
	/opt/sbase/bin/halt -p;;
*)
	echo "USAGE: rc init|reboot|shutdown"
	echo "   rc init       initilize the system"
	echo "   rc reboot     reboot the system"
	echo "   rc shutdown   shutdown the system"
	echo "NOTE: rc should never be used directly (rc init at least)";;
esac
